# Compilateur
CC = gcc
RM = rm -f
TARGET = app.exe

# ============================================
# LISTE UNIQUEMENT LES FICHIERS .c (pas les dossiers, pas les .h)
# ============================================
SOURCES = \
    main.c \
    AppGTK/AppGTK.c \
    ParserXML/FUNC_SIGNAL.c \
    ParserXML/GESTION_PILE.c \
    ParserXML/GESTION_SIGNAL.c \
    ParserXML/PARSER_FUNC.c \
    Widget/APPLY_FUNC/APPLY_ATTRIBUT_BOX.c \
    Widget/APPLY_FUNC/APPLY_ATTRIBUT_BUTTON.c \
    Widget/APPLY_FUNC/APPLY_ATTRIBUT_BUTTON_BOX.c \
    Widget/APPLY_FUNC/APPLY_ATTRIBUT_BUTTONRADIO.c \
    Widget/APPLY_FUNC/APPLY_ATTRIBUT_CHECKBUTTON.c \
    Widget/APPLY_FUNC/APPLY_ATTRIBUT_CHECKMENUITEM.c \
    Widget/APPLY_FUNC/APPLY_ATTRIBUT_COLORBUTTON.c \
    Widget/APPLY_FUNC/APPLY_ATTRIBUT_COMBOBOXTEXT.c \
    Widget/APPLY_FUNC/APPLY_ATTRIBUT_ENTRY.c \
    Widget/APPLY_FUNC/APPLY_ATTRIBUT_EXPANDER.c \
    Widget/APPLY_FUNC/APPLY_ATTRIBUT_FENETRE.c \
    Widget/APPLY_FUNC/APPLY_ATTRIBUT_FILECHOOSEBUTTON.c \
    Widget/APPLY_FUNC/APPLY_ATTRIBUT_FLOWBOX.c \
    Widget/APPLY_FUNC/APPLY_ATTRIBUT_FONTBUTTON.c \
    Widget/APPLY_FUNC/APPLY_ATTRIBUT_FRAME.c \
    Widget/APPLY_FUNC/APPLY_ATTRIBUT_GRID.c \
    Widget/APPLY_FUNC/APPLY_ATTRIBUT_HEADERBAR.c \
    Widget/APPLY_FUNC/APPLY_ATTRIBUT_IMAGE.c \
    Widget/APPLY_FUNC/APPLY_ATTRIBUT_INFOBAR.c \
    Widget/APPLY_FUNC/APPLY_ATTRIBUT_LABEL.c \
    Widget/APPLY_FUNC/APPLY_ATTRIBUT_LAYOUT.c \
    Widget/APPLY_FUNC/APPLY_ATTRIBUT_LEVELBAR.c \
    Widget/APPLY_FUNC/APPLY_ATTRIBUT_LINKBUTTON.c \
    Widget/APPLY_FUNC/APPLY_ATTRIBUT_LISTBOX.c \
    Widget/APPLY_FUNC/APPLY_ATTRIBUT_MENUBUTTON.c \
    Widget/APPLY_FUNC/APPLY_ATTRIBUT_MENUITEM.c \
    Widget/APPLY_FUNC/APPLY_ATTRIBUT_NOTEBOOK.c \
    Widget/APPLY_FUNC/APPLY_ATTRIBUT_PANED.c \
    Widget/APPLY_FUNC/APPLY_ATTRIBUT_PROGRESSBAR.c \
    Widget/APPLY_FUNC/APPLY_ATTRIBUT_RADIOMENUITEM.c \
    Widget/APPLY_FUNC/APPLY_ATTRIBUT_REVEALER.c \
    Widget/APPLY_FUNC/APPLY_ATTRIBUT_SCALE.c \
    Widget/APPLY_FUNC/APPLY_ATTRIBUT_SCALEBUTTON.c \
    Widget/APPLY_FUNC/APPLY_ATTRIBUT_SCROLLBAR.c \
    Widget/APPLY_FUNC/APPLY_ATTRIBUT_SEARCHBAR.c \
    Widget/APPLY_FUNC/APPLY_ATTRIBUT_SEPARATOR.c \
    Widget/APPLY_FUNC/APPLY_ATTRIBUT_SPINBUTTON.c \
    Widget/APPLY_FUNC/APPLY_ATTRIBUT_SPINNER.c \
    Widget/APPLY_FUNC/APPLY_ATTRIBUT_STACK.c \
    Widget/APPLY_FUNC/APPLY_ATTRIBUT_SWITCH.c \
    Widget/APPLY_FUNC/APPLY_ATTRIBUT_TOGGLEBUTTON.c \
    Widget/APPLY_FUNC/APPLY_ATTRIBUT_TOOLBAR.c \
    Widget/APPLY_FUNC/APPLY_ATTRIBUT_TOOLITEM.c \
    Widget/APPLY_FUNC/APPLY_CSS.c \
    Widget/GENERAL/Widget.c \
Widget/INIT_FUNC/INIT_FUNC_ACTIONBAR.c \
Widget/INIT_FUNC/INIT_FUNC_BOX.c \
Widget/INIT_FUNC/INIT_FUNC_BUTTON.c \
Widget/INIT_FUNC/INIT_FUNC_BUTTON_BOX.c \
Widget/INIT_FUNC/INIT_FUNC_BUTTONRADIO.c \
Widget/INIT_FUNC/INIT_FUNC_CALENDRIER.c \
Widget/INIT_FUNC/INIT_FUNC_CHECKBUTTON.c \
Widget/INIT_FUNC/INIT_FUNC_CHECKMENUITEM.c \
Widget/INIT_FUNC/INIT_FUNC_COLORBUTTON.c \
Widget/INIT_FUNC/INIT_FUNC_COMBOBOXTEXT.c \
Widget/INIT_FUNC/INIT_FUNC_ENTRY.c \
Widget/INIT_FUNC/INIT_FUNC_EXPANDER.c \
Widget/INIT_FUNC/INIT_FUNC_FENETRE.c \
Widget/INIT_FUNC/INIT_FUNC_FILECHOOSEBUTTON.c \
Widget/INIT_FUNC/INIT_FUNC_FIXED.c \
Widget/INIT_FUNC/INIT_FUNC_FLOWBOX.c \
Widget/INIT_FUNC/INIT_FUNC_FONTBUTTON.c \
Widget/INIT_FUNC/INIT_FUNC_FRAME.c \
Widget/INIT_FUNC/INIT_FUNC_GRID.c \
Widget/INIT_FUNC/INIT_FUNC_HEADERBAR.c \
Widget/INIT_FUNC/INIT_FUNC_IMAGE.c \
Widget/INIT_FUNC/INIT_FUNC_INFOBAR.c \
Widget/INIT_FUNC/INIT_FUNC_LABEL.c \
Widget/INIT_FUNC/INIT_FUNC_LAYOUT.c \
Widget/INIT_FUNC/INIT_FUNC_LEVELBAR.c \
Widget/INIT_FUNC/INIT_FUNC_LINKBUTTON.c \
Widget/INIT_FUNC/INIT_FUNC_LISTBOX.c \
Widget/INIT_FUNC/INIT_FUNC_MENU.c \
Widget/INIT_FUNC/INIT_FUNC_MENUBAR.c \
Widget/INIT_FUNC/INIT_FUNC_MENUBUTTON.c \
Widget/INIT_FUNC/INIT_FUNC_MENUITEM.c \
Widget/INIT_FUNC/INIT_FUNC_NOTEBOOK.c \
Widget/INIT_FUNC/INIT_FUNC_OPTION.c \
Widget/INIT_FUNC/INIT_FUNC_OVERLAY.c \
Widget/INIT_FUNC/INIT_FUNC_PANED.c \
Widget/INIT_FUNC/INIT_FUNC_PROGRESSBAR.c \
Widget/INIT_FUNC/INIT_FUNC_RADIOMENUITEM.c \
Widget/INIT_FUNC/INIT_FUNC_REVEALER.c \
Widget/INIT_FUNC/INIT_FUNC_SCALE.c \
Widget/INIT_FUNC/INIT_FUNC_SCALEBUTTON.c \
Widget/INIT_FUNC/INIT_FUNC_SCROLLBAR.c \
Widget/INIT_FUNC/INIT_FUNC_SEARCHBAR.c \
Widget/INIT_FUNC/INIT_FUNC_SEPARATOR.c \
Widget/INIT_FUNC/INIT_FUNC_SEPARATORMENUITEM.c \
Widget/INIT_FUNC/INIT_FUNC_SEPARATORTOOLITEM.c \
Widget/INIT_FUNC/INIT_FUNC_SIGNAL.c \
Widget/INIT_FUNC/INIT_FUNC_SPINBUTTON.c \
Widget/INIT_FUNC/INIT_FUNC_SPINNER.c \
Widget/INIT_FUNC/INIT_FUNC_STACK.c \
Widget/INIT_FUNC/INIT_FUNC_STACKSWITCHER.c \
Widget/INIT_FUNC/INIT_FUNC_STATUSBAR.c \
Widget/INIT_FUNC/INIT_FUNC_SWITCH.c \
Widget/INIT_FUNC/INIT_FUNC_TOGGLEBUTTON.c \
Widget/INIT_FUNC/INIT_FUNC_TOOLBAR.c \
Widget/INIT_FUNC/INIT_FUNC_TOOLITEM.c \
    Widget/SET_CHILD_FUNC/CONTROLE_PARENTE.c \
    Widget/SET_CHILD_FUNC/SET_CHILD_ACTIONBAR.c \
    Widget/SET_CHILD_FUNC/SET_CHILD_BOX.c \
    Widget/SET_CHILD_FUNC/SET_CHILD_COMBOBOXTEXT.c \
    Widget/SET_CHILD_FUNC/SET_CHILD_DEFAULT.c \
    Widget/SET_CHILD_FUNC/SET_CHILD_FENETRE.c \
    Widget/SET_CHILD_FUNC/SET_CHILD_FIXED.c \
    Widget/SET_CHILD_FUNC/SET_CHILD_FLOWBOX.c \
    Widget/SET_CHILD_FUNC/SET_CHILD_GRID.c \
    Widget/SET_CHILD_FUNC/SET_CHILD_LAYOUT.c \
    Widget/SET_CHILD_FUNC/SET_CHILD_LISTBOX.c \
    Widget/SET_CHILD_FUNC/SET_CHILD_MENU.c \
    Widget/SET_CHILD_FUNC/SET_CHILD_MENUBAR.c \
    Widget/SET_CHILD_FUNC/SET_CHILD_MENUBUTTON.c \
    Widget/SET_CHILD_FUNC/SET_CHILD_MENUITEM.c \
    Widget/SET_CHILD_FUNC/SET_CHILD_NOTEBOOK.c \
    Widget/SET_CHILD_FUNC/SET_CHILD_OVERLAY.c \
    Widget/SET_CHILD_FUNC/SET_CHILD_PANED.c \
    Widget/SET_CHILD_FUNC/SET_CHILD_SEARCHBAR.c \
    Widget/SET_CHILD_FUNC/SET_CHILD_STACK.c \
    Widget/SET_CHILD_FUNC/SET_CHILD_TOOLBAR.c

# ============================================
# DOSSIERS CONTENANT LES .h (pour les includes)
# ============================================
INC_DIRS = \
    . \
    AppGTK \
    ParserXML \
    Widget \
    Simulation \
    Interface_macro \
    Widget/APPLY_FUNC \
    Widget/GENERAL \
    Widget/INIT_FUNC \
    Widget/SET_CHILD_FUNC

# ============================================
# CONFIGURATION COMPILATION
# ============================================
INC_FLAGS = $(addprefix -I,$(INC_DIRS))
GTK_CFLAGS = $(shell pkg-config --cflags gtk+-3.0)
GTK_LIBS = $(shell pkg-config --libs gtk+-3.0)

CFLAGS = -Wall -g $(INC_FLAGS) $(GTK_CFLAGS)
LDFLAGS = $(GTK_LIBS)

# ============================================
# CRÉATION DES OBJECTS (en conservant la structure des dossiers)
# ============================================
# IMPORTANT : On garde les chemins complets dans obj/
# Par exemple : obj/Widget/APPLY_FUNC/APPLY_ATTRIBUT_BOX.o
OBJECTS = $(addprefix obj/,$(SOURCES:.c=.o))

# ============================================
# RÈGLES DE COMPILATION
# ============================================
all: $(TARGET)

# Édition des liens
$(TARGET): $(OBJECTS)
	$(CC) $^ -o $@ $(LDFLAGS)
	@echo "Compilation terminée ! Exécutez ./$(TARGET)"

# Règle générique pour compiler TOUS les .c où qu'ils se trouvent
# Cette règle fonctionne pour les fichiers dans n'importe quel sous-dossier
obj/%.o: %.c
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) -c $< -o $@

# Nettoyage
clean:
	rm -rf obj $(TARGET)

.PHONY: all clean